[package]
name = "bitcoin-block-parser"
version = "0.1.1"
edition = "2021"
authors = ["Saigo Nanshu"]
license = "MIT"
repository = "https://github.com/sumopool/bitcoin-block-parser"
readme = "README.md"
description = "Fast optimized parser for the bitcoin `blocks` data with UTXO tracking."
categories = ["cryptography::cryptocurrencies"]
keywords = [ "crypto", "bitcoin" ]
documentation = "https://docs.rs/bitcoin-block-parser"

[dependencies]
bitcoin = "0.32.2"
anyhow = "1.0.88"
threadpool = "1.8.1"
rustc-hash = "2.0.0"
crossbeam-channel = "0.5.13"
# Could make the following deps into features
postcard = { version = "1.0.10", features = ["use-std"] }
scalable_cuckoo_filter = { version = "0.3.2", features = ["serde_support"] }
clap = { version = "4.5.16", features = ["derive"] }
rand = "0.8.5"